version: '3.8'

services:
  asset-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - BALLERINA_DEV_MODE=true
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/faculties"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
